
executor: "CeleryExecutor"

dags:
  persistence:
    enabled: true
    size: 1Gi
  gitSync:
    enabled: true
    repo: "https://github.com/my-org/airflow-dags.git"
    branch: main

workers:
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

web:
  service:
    type: ClusterIP


postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow
